use std::collections::HashMap;

#[cfg(test)]
pub fn encode<T: AsRef<str>>(source: T) -> String {
    let source = source.as_ref();
    let map = Base64BitMap::new();
    let mut iter = Base64BitStreamIter::new(source);
    iter.encode(map)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
struct Base64BitStream {
    stream: [Bit; 6],
}
impl Base64BitStream {
    fn new(stream: [Bit; 6]) -> Self {
        Self { stream }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
enum Bit {
    Zero,
    One,
}
struct BitIter {
    bits: Vec<Bit>,
}
impl BitIter {
    fn new(source: &str) -> Self {
        let bits =
            source
                .bytes()
                .map(|byte| Bit::from_byte(byte))
                .fold(Vec::new(), |mut acc, mut cur| {
                    for c in cur {
                        acc.push(c);
                    }
                    acc
                });
        Self { bits }
    }
}
impl Iterator for BitIter {
    type Item = Bit;
    fn next(&mut self) -> Option<Self::Item> {
        if self.bits.len() == 0 {
            return None;
        };
        Some(self.bits.remove(0))
    }
}
impl Bit {
    fn str_to_bit_iter(source: &str) -> BitIter {
        BitIter::new(source)
    }
    fn from_byte(byte: u8) -> [Bit; 8] {
        let mut bits = [Bit::Zero; 8];
        (0..8).for_each(|i| {
            let bit = (byte >> (7 - i)) & 1;
            match bit {
                0 => bits[i] = Bit::Zero,
                1 => bits[i] = Bit::One,
                _ => panic!("not 1 or 0 {}", bit),
            }
        });
        bits
    }
}
mod base64_tests {
    use super::*;
    #[test]
    fn from_byte_test() {
        assert_eq!(Bit::from_byte(0), [Bit::Zero; 8]);
        assert_eq!(
            Bit::from_byte(1),
            [
                Bit::Zero,
                Bit::Zero,
                Bit::Zero,
                Bit::Zero,
                Bit::Zero,
                Bit::Zero,
                Bit::Zero,
                Bit::One,
            ]
        );
        assert_eq!(
            Bit::from_byte(254),
            [
                Bit::One,
                Bit::One,
                Bit::One,
                Bit::One,
                Bit::One,
                Bit::One,
                Bit::One,
                Bit::Zero,
            ]
        );
    }
    #[test]
    fn base64_test() {
        let source = "Hello,World!";
        let encode = encode(source);
        assert_eq!(encode, "SGVsbG8sV29ybGQh".to_string());
    }
}
struct Base64BitStreamIter {
    bit_iter: BitIter,
}
impl Base64BitStreamIter {
    fn new(source: &str) -> Self {
        Self {
            bit_iter: Bit::str_to_bit_iter(source),
        }
    }
    fn encode(&mut self, map: Base64BitMap) -> String {
        let mut result = String::new();
        let mut base64 = self.pop_base64_bit();
        while base64.is_some() {
            let key = base64.unwrap();
            let value = map.0.get(&key).unwrap();
            result.push(*value);
            base64 = self.pop_base64_bit();
        }
        result
    }
    fn pop_base64_bit(&mut self) -> Option<Base64BitStream> {
        let mut stream = [Bit::Zero; 6];
        for i in 0..6 {
            let bit = self.bit_iter.next();
            if bit.is_none() {
                return None;
            }
            stream[i] = bit.unwrap().clone()
        }
        Some(Base64BitStream { stream })
    }
    //fn
}
struct Base64BitMap(HashMap<Base64BitStream, char>);
impl Base64BitMap {
    fn new() -> Self {
        let map = [
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'A',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                'B',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                'C',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
                'D',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'E',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
                'F',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
                'G',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                ]),
                'H',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'I',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                'J',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                'K',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
                'L',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'M',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
                'N',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
                'O',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                ]),
                'P',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'Q',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                'R',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                'S',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
                'T',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'U',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
                'V',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
                'W',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                ]),
                'X',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'Y',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                'Z',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                'a',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
                'b',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'c',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
                'd',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
                'e',
            ),
            (
                Base64BitStream::new([Bit::Zero, Bit::One, Bit::One, Bit::One, Bit::One, Bit::One]),
                'f',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'g',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                'h',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                'i',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
                'j',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'k',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
                'l',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
                'm',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                ]),
                'n',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'o',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                'p',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                'q',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
                'r',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                's',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
                't',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
                'u',
            ),
            (
                Base64BitStream::new([Bit::One, Bit::Zero, Bit::One, Bit::One, Bit::One, Bit::One]),
                'v',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'w',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                'x',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                'y',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
                'z',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                '0',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
                '1',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
                '2',
            ),
            (
                Base64BitStream::new([Bit::One, Bit::One, Bit::Zero, Bit::One, Bit::One, Bit::One]),
                '3',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                '4',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                '5',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                '6',
            ),
            (
                Base64BitStream::new([Bit::One, Bit::One, Bit::One, Bit::Zero, Bit::One, Bit::One]),
                '7',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                '8',
            ),
            (
                Base64BitStream::new([Bit::One, Bit::One, Bit::One, Bit::One, Bit::Zero, Bit::One]),
                '9',
            ),
            (
                Base64BitStream::new([Bit::One, Bit::One, Bit::One, Bit::One, Bit::One, Bit::Zero]),
                '+',
            ),
            (
                Base64BitStream::new([Bit::One, Bit::One, Bit::One, Bit::One, Bit::One, Bit::One]),
                '/',
            ),
        ]
        .into_iter()
        .collect();
        Self(map)
    }
}
