use std::collections::HashMap;

use super::bits::{Base64BitStream, Bit};

pub struct Base64BitMap(pub HashMap<Base64BitStream, char>);
impl Base64BitMap {
    pub fn new() -> Self {
        let map = [
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'A',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                'B',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                'C',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
                'D',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'E',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
                'F',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
                'G',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                ]),
                'H',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'I',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                'J',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                'K',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
                'L',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'M',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
                'N',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
                'O',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                ]),
                'P',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'Q',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                'R',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                'S',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
                'T',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'U',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
                'V',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
                'W',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                ]),
                'X',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'Y',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                'Z',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                'a',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
                'b',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'c',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
                'd',
            ),
            (
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
                'e',
            ),
            (
                Base64BitStream::new([Bit::Zero, Bit::One, Bit::One, Bit::One, Bit::One, Bit::One]),
                'f',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'g',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                'h',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                'i',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
                'j',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'k',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
                'l',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
                'm',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                ]),
                'n',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'o',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                'p',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                'q',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
                'r',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                's',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
                't',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
                'u',
            ),
            (
                Base64BitStream::new([Bit::One, Bit::Zero, Bit::One, Bit::One, Bit::One, Bit::One]),
                'v',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                'w',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                'x',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                'y',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
                'z',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                '0',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
                '1',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
                '2',
            ),
            (
                Base64BitStream::new([Bit::One, Bit::One, Bit::Zero, Bit::One, Bit::One, Bit::One]),
                '3',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                '4',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
                '5',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
                '6',
            ),
            (
                Base64BitStream::new([Bit::One, Bit::One, Bit::One, Bit::Zero, Bit::One, Bit::One]),
                '7',
            ),
            (
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
                '8',
            ),
            (
                Base64BitStream::new([Bit::One, Bit::One, Bit::One, Bit::One, Bit::Zero, Bit::One]),
                '9',
            ),
            (
                Base64BitStream::new([Bit::One, Bit::One, Bit::One, Bit::One, Bit::One, Bit::Zero]),
                '+',
            ),
            (
                Base64BitStream::new([Bit::One, Bit::One, Bit::One, Bit::One, Bit::One, Bit::One]),
                '/',
            ),
        ]
        .into_iter()
        .collect();
        Self(map)
    }
}
