use std::collections::HashMap;

use super::bits::{Base64BitStream, Bit};

pub struct Base64BitMap(pub HashMap<char, Base64BitStream>);

impl Base64BitMap {
    pub fn new() -> Self {
        let map = [
            (
                'A',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                'B',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                'C',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                'D',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
            ),
            (
                'E',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                'F',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                'G',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                'H',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                ]),
            ),
            (
                'I',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                'J',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                'K',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                'L',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
            ),
            (
                'M',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                'N',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                'O',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                'P',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                ]),
            ),
            (
                'Q',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                'R',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                'S',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                'T',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
            ),
            (
                'U',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                'V',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                'W',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                'X',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                ]),
            ),
            (
                'Y',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                'Z',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                'a',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                'b',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
            ),
            (
                'c',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                'd',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                'e',
                Base64BitStream::new([
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                'f',
                Base64BitStream::new([Bit::Zero, Bit::One, Bit::One, Bit::One, Bit::One, Bit::One]),
            ),
            (
                'g',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                'h',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                'i',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                'j',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
            ),
            (
                'k',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                'l',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                'm',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                'n',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                ]),
            ),
            (
                'o',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                'p',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                'q',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                'r',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
            ),
            (
                's',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                't',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                'u',
                Base64BitStream::new([
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                'v',
                Base64BitStream::new([Bit::One, Bit::Zero, Bit::One, Bit::One, Bit::One, Bit::One]),
            ),
            (
                'w',
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                'x',
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                'y',
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                'z',
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                ]),
            ),
            (
                '0',
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                '1',
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                '2',
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                '3',
                Base64BitStream::new([Bit::One, Bit::One, Bit::Zero, Bit::One, Bit::One, Bit::One]),
            ),
            (
                '4',
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                '5',
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                    Bit::One,
                ]),
            ),
            (
                '6',
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::One,
                    Bit::Zero,
                ]),
            ),
            (
                '7',
                Base64BitStream::new([Bit::One, Bit::One, Bit::One, Bit::Zero, Bit::One, Bit::One]),
            ),
            (
                '8',
                Base64BitStream::new([
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::One,
                    Bit::Zero,
                    Bit::Zero,
                ]),
            ),
            (
                '9',
                Base64BitStream::new([Bit::One, Bit::One, Bit::One, Bit::One, Bit::Zero, Bit::One]),
            ),
            (
                '+',
                Base64BitStream::new([Bit::One, Bit::One, Bit::One, Bit::One, Bit::One, Bit::Zero]),
            ),
            (
                '/',
                Base64BitStream::new([Bit::One, Bit::One, Bit::One, Bit::One, Bit::One, Bit::One]),
            ),
        ]
        .into_iter()
        .collect();
        Self(map)
    }
}
